name: 'deGov - Rich Text Format - Settings'
description: 'Activates Spamspan obfuscation of the E-Mail addresses for the Richt Text Format'
type: module
core: 8.x
dependencies:
  - ckeditor
  - editor
  - entity_embed
  - filter
  - lightning_media
  - spamspan
