name: 'deGov - Rich Text Format - Settings'
description: 'Activates Spamspan obfuscation of the E-Mail addresses for the Richt Text Format'
type: module
package: deGov
core: 8.x
dependencies:
  - ckeditor
  - editor
  - embed
  - entity_embed
  - filter
  - linkit
  - media_entity
  - node
  - spamspan
